### ISSUE TITLE
Write da' freaking wiki

### ISSUE THREAD

**Issue by EnriqueVidal** [cloverinteractive/cms#10]
Aside of the README file this project has no documentation whatsoever, we need to start the wiki, current topics we should discuss:
- Deployment
- jRuby
- Creating themes
- Extending the CMS

**Comment by EnriqueVidal** [comment]
Besides the points I just wrote any other ideas?

**Comment by EnriqueVidal** [comment]
These two look like good topics too
- Git Workflow
- Review Workflow

**Comment by aalvarado** [comment]
the git workflow is particularly interesting because it lets other people contribute code more easily. +1 for git wf

**Comment by ghost** [comment]
I opened up the Wiki, going to try to come up with a shitty first draft of the Code Review workflow
