### ISSUE TITLE
Make the ci pass

### ISSUE THREAD

**Issue by EnriqueVidal** [cloverinteractive/cms#8]
We need to figure out why does our build fails with travis an fix it.

**Comment by ghost** [comment]
Apparently, the problem may be jRuby, possibly an outdated gem.

**Comment by EnriqueVidal** [comment]
The problem is that the travis-ci crew removed native support for java, even though our Gemfile includes java versions of each of the gems required when we run bundle install multiple times on the same project we end up with a mixture of native `bcrypt` and java `bcrypt` which is not good.

We only have two options:

1) Ditch JRuby from the ci and add instructions to README and wiki
2) Stop versioning `Gemfile.lock`

The latter is risky, I know many people prefer to work with the JVM, but its not how we're deploying right now so I'll go for the first options which I believe matches us and mostly anyone who has used or is using the CMS.

I'm taking over this issue.

**Comment by EnriqueVidal** [comment]
`issue8` branch is ready for review, please remember to update the commit comment to include the closes clause.

**Comment by ghost** [comment]
For sure, I'll take on the review.
