### ISSUE TITLE
Upgrade to rails 3.1

### ISSUE THREAD

**Issue by EnriqueVidal** [cloverinteractive/cms#9]
Currently not possible because acl9 does not work with rails 3.1 and there is no work around yet. I have forked the project inside cloverinteractive however I was unable to run their tests, we need to:
- Figure out a way to run their tests to make our own fix that will work with rails 3.1 ( That should be a ticket in that project )
- Second option is wait until acl9 reaches that point (which might take some time therefore making it an undesirable solution)
- Talk to the guys involved in the project, figure how to contribute, and migrate the app to rails 3.1

**Comment by ghost** [comment]
Ok, well now it's possible since we're ditching RBAC, yeah!

Taking it ova' from here.

**Comment by ghost** [comment]
Is that swank code bar new on the github ui? It's sharp.
